.prettierrc, client/package.json, client/postcss.config.js, client/src/index.css, client/src/main.tsx, client/tailwind.config.js, package-lock.json, package.json
resolve #18 
1.5
- tailwind CSS 설정
- [CSS-in-JS vs. Zero-runtime vs. Utility-First CSS](https://www.notion.so/CSS-in-JS-vs-Zero-runtime-vs-Utility-First-CSS-89d5d30877e6471e9ee25ec3e69c80cf?pvs=4)
=> <FE> 스타일 라이브러리 설정

client/package.json, client/vite.config.ts, package-lock.json
close #21 
0.5
- React 테스트 라이브러리 + vitest 설정
- [테스트 라이브러리](https://www.notion.so/0d2a447733654e748810a6ac57e7b077?pvs=4)
=> <FE> 테스팅 환경 설정

client/eslint.config.js, eslint.config.js
=> <FE> client 폴더 ESLint 설정 문제 해결

package-lock.json, server/package.json, server/src/app.module.ts, server/src/signaling-server/signaling-server.gateway.ts, server/winston.config.ts
resolve #83
3시간
- winston logger nest 환경에 설치
- winston logger 환경설정
- winston logger 기존 gateway에 적용
- .log 파일에 저장할 때 log 형식에 대한 고민 (JSON vs Console 출력형식)
- https://www.notion.so/Logger-2fa0139ebf5e460db476fc0de9678a96
=> <BE> nestjs logger 환경 설정 및 적용을 완료한다.

server/src/app.module.ts, server/src/chatting-server/chatting-server.gateway.spec.ts, server/src/chatting-server/chatting-server.gateway.ts, server/src/chatting-server/chatting-server.module.ts, server/src/study-room/mock.repository.ts, server/src/study-room/study-room.service.ts
resolve #11
resolve #45 
resolve #80 
3시간
- `chatting-server` gateway 생성 : 현재는 signalling-server, chatting-server 연결 시, 소켓이 다르다고 가정하여 작성하였습니다.
- joinRoom : 방 입장 요청
- leaveRoom : 방 퇴장 요청
- sendMessage : 메시지 전송
=> <BE> 웹소켓 채팅 서버 설정을 완료한다.

package-lock.json, server/package.json, server/src/signaling-server/signaling-server.module.ts, server/test/app.e2e-spec.ts
#14
5시간
- nestjs 시그널링 서버 socketio 테스트 코드 작성
- `/server/test/app.e2e-spec.ts` 파일에 e2e 테스트 코드 작성
- `npm run test:e2e` 명령으로 테스트 통과 되는거 확인
- https://foamy-rose-f4f.notion.site/nestjs-Cannot-find-module-5478bf092fe14e018e96335cf1f9a03e
- https://dev.to/jfrancai/demystifying-nestjs-websocket-gateways-a-step-by-step-guide-to-effective-testing-1a1f
=> <BE> 시그널링 서버 테스트 코드 작성

server/src/chatting-server/chatting-server.gateway.spec.ts, server/src/chatting-server/chatting-server.gateway.ts, server/src/study-room/mock.repository.ts, server/src/study-room/study-room.controller.spec.ts, server/src/study-room/study-room.controller.ts, server/src/study-room/study-room.entity.ts, server/src/study-room/study-room.module.ts, server/src/study-room/study-room.service.spec.ts, server/src/study-room/study-room.service.ts
resolve #10
4시간
- study-room module에 대한 api 작성
- 공부방 생성 + 전체 공부방 리스트 반환 구현
- 위의 개발 내용에 대한 테스트 코드 작성
- test 코드 작성시 의존성 주입 설정을 해줘야 합니다.
- 예를 들어 controller -> service -> repository 형식으로 참조하고 있을 때, 
- controller.spec.ts에서 테스트 코드를 작성할 때 service뿐만 아니라 repository도 provider에 추가해야 합니다.
- https://www.notion.so/4e85c1fdc265402e9526676132b008bc?v=88054bde3de042a9bed8a84700b723d3&p=c1c909d522cb489f9fd4cf91a370b1da&pm=s
=> <BE> 공부방 관련 API 서버 구현(DB X) + 테스트

client/package.json, client/src/App.tsx, client/src/components/Home.tsx, client/src/components/Home/Home.tsx, client/src/components/StudyRoom/StudyRoom.tsx, client/src/components/common/ProtectedRoute.tsx, package-lock.json
resolve #102 
1
- 메인 페이지(`/`)에서 `로그인없이 이용하기` 버튼을 누르지 않고 URL(`/studyroom`)로 직접 공부방 페이지에 접근할 경우 메인 페이지로 리다이렉트 되도록 구현
- `로그인없이 이용하기` 버튼을 누르면 localStrage에 `userId`가 부여되고 공부방 페이지로 이동
=> <FE> 3주차 데모용 React Router 설정

package-lock.json, server/package.json, server/src/app.module.ts
resolve #12 
resolve #13 
1시간
- mysql2 설치
- typeorm 설치
- 스키마 정리
https://www.erdcloud.com/d/WzTGn3CBrx3DCChvz
=> <BE> 데이터베이스 설정을 완료한다.

server/src/main.ts
resolve #122 
20분
- main.ts에서 전역으로 CORS 허용
```ts
app.enableCors({
origin: '*',
methods: 'GET,HEAD,PUT,POST,DELETE,PATCH',
credentials: true,
});
```
- 이후에 특정 controller나 모듈에 적용하려면 별도 처리 필요
=> <BE> 랜덤 닉네임 CORS 에러 수정 

server/src/study-room/study-room.module.ts
resolve #128 
5분
- 개발할 사항1
- 개발할 사항2
- 구현한 개발 화면이나 영상을 첨부해 주세요 (생략 가능)
=> <BE> StudyRoomRepository 경로 오류 수정

server/src/signaling-server/signaling-server.gateway.ts, server/src/study-room/entity/study-room-participant.entity.ts, server/src/study-room/repository/study-room-participant.repository.spec.ts, server/src/study-room/repository/study-room-participant.repository.ts, server/src/study-room/study-room.controller.spec.ts, server/src/study-room/study-room.controller.ts, server/src/study-room/study-room.service.spec.ts, server/src/study-room/study-room.service.ts
resolve #127 
1시간
- `study-room-participant` entity에서 nickname 속성 삭제
- 
=> <BE> `study-room-participant` entity에서 nickname 속성 삭제

server/src/signaling-server/signaling-server.gateway.ts, server/src/study-room/entity/category.entity.ts, server/src/study-room/entity/study-room-participant.entity.ts, server/src/study-room/entity/study-room.entity.ts, server/src/study-room/study-room.controller.ts, server/src/study-room/study-room.service.ts, server/src/user/user.entity.ts
resolve #63 
resolve #70 
resolve #74 
3시간 
- 공부방 생성 API 구현
- 공부방 리스트 반환 API 구현
- 공부방 입장 확인(비밀번호 or 방 존재확인) API 구현.
- 실제 DB랑 연동가능
- 입장 확인에 대한 에러처리.(서비스에서 반환 vs 컨트롤러에서 처리)
- https://www.notion.so/API-c1c909d522cb489f9fd4cf91a370b1da
=> <BE> 공부방 목록,생성,입장확인 API를 만든다.

client/src/components/Demo.tsx
resolve #137 
20분
- SignalingClient 시그니처 수정으로 인한 Demo 컴포넌트 빌드 에러 수정
=> <FE> client 폴더 빌드 에러 수정

client/src/socket/signalingClient.ts
resolve #142 
0.5
- Signaling Process Payload 변경으로 인한 오류 수정
=> <FE> signalingClient 연결 오류 수정

client/src/components/StudyRoom/StudyRoom.tsx, client/src/components/StudyRoom/StudyRoomHeader.tsx, client/src/components/StudyRoomList/AddItemModal.tsx, client/src/components/StudyRoomList/ItemCard.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx, client/src/components/StudyRoomList/index.tsx, client/src/constants/CATEGORY_NAMES.ts, client/src/hooks/useWebRTC.ts, client/src/socket/signalingClient.ts, package-lock.json
resolve #145 
2시간
- npm install 시 발생하는 취약점 경고 해결
- Signaling 소켓 이벤트 페이로드를 서버에 맞춰 수정
- 쿼리파라미터로 roomId를 받아 공부방에 입장하도록 수정
- 공부방에 입장 시 쿼리파라미터로 roomId를 넘기도록 수정
=> <FE> Signaling 서버 이벤트 변경으로 인한 수정

client/src/socket/signalingClient.ts
resolve #153 
0.5
- 피어 연결 과정에서 비동기 작업으로 인한 오류 수정
=> <FE> 피어 연결 과정에서 비동기 작업으로 인한 오류 수정

client/src/components/StudyRoom/StudyRoom.tsx, client/src/components/StudyRoom/StudyRoomHeader.tsx, client/src/components/StudyRoomList/Header.tsx, client/src/components/StudyRoomList/index.tsx
resolve #60
1
- 브라우저에 하루 누적 공부 시간 저장 구현
- 공부방 리스트 페이지에 하루 누적 공부 시간 표시
=> <FE> 하루 누적 공부 시간 저장 구현

server/src/chatting-server/chatting-server.gateway.ts
resolve #157 
30분
- sendMessage 시, 다른 클라이언트에서 message가 안 오는 현상 수정
=> <BE> sendMessage 시, 다른 클라이언트에서 message가 안 오는 현상 수정

server/test/app.e2e-spec.ts
resolve #160
2시간
- SignalingServerGateway 필요한 모듈(서비스) 모킹
- joinRoom 이벤트까지 포함하는 e2e 테스트 코드 작성
- 서비스 로직 모킹 하는법
- https://docs.nestjs.com/fundamentals/testing#end-to-end-testing
=> <BE> 시그널링 서버 joinRoom e2e 테스트 코드 작성

server/src/study-room/repository/study-room.repository.ts, server/src/study-room/study-room.service.ts
resolve #168 
20분
- repository에서 
=> <BE> 방 리스트 api 수정

server/src/signaling-server/signaling-server.dto.ts, server/src/signaling-server/signaling-server.gateway.ts, server/test/app.e2e-spec.ts
=> <BE> iceCandidate를 candidate로 수정

client/src/components/StudyRoom/Chat.tsx, client/src/components/StudyRoom/StudyRoom.tsx, client/src/components/StudyRoom/VideoGrid.tsx, client/src/components/common/StopWatch.tsx, client/src/hooks/useWebRTC.ts
resolve #172 
1
- keyDown 이벤트 중복 실행 문제 해결
- 채팅 기능 구현
- 스톱워치 애니메이션 적용
- 불필요한 border 삭제
- [isComposing](https://jjang-j.tistory.com/123)
- [스톱워치 애니메이션](https://cruip.com/creating-a-sliding-text-animation-with-tailwind-css/)
=> <FE> 채팅 기능 구현 마무리

client/src/App.tsx, client/src/components/StudyRoom/StudyRoom.tsx, client/src/components/StudyRoomList/Header.tsx, client/src/components/StudyRoomList/ItemCard.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx, client/src/components/StudyRoomList/index.tsx
resolve #62 
1
- 공부방 페이지 url 변경
- 공부방 리스트 조회 api 연결
=> <FE> 공부방 리스트 조회 api 연결

client/src/components/StudyRoomList/ItemCard.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx, client/src/components/StudyRoomList/index.tsx, client/src/utils/shuffle.ts, client/tsconfig.app.json, client/vite.config.ts
resolve #73 
1.5시간
- 공개방/비밀방 입장 체크 API 연결
=> <FE> 공개방/비밀방 입장 체크 API 연결

package-lock.json, server/src/signaling-server/signaling-server.gateway.ts, server/src/study-room/repository/study-room.repository.ts, server/src/study-room/study-room.service.ts
resolve #51
2시간
- 마지막 사용자가 공부방을 나가면 5분 타이머 시작.
- 5분 후 해당 방 삭제
- 중간에 다른 사용자가 들어올 경우 타이머 제거
```ts
// joinRoom
const room = this.rooms.get(roomId);
if (!room) {
this.rooms.set(roomId, { timer: null });
} else {
if (room.timer) {
clearTimeout(room.timer);
room.timer = undefined;
}
}
```
```ts
// handleDisconnect
const room = this.rooms.get(roomId);
if (!users.length) {
room.timer = setTimeout(
() => {
this.rooms.delete(roomId);
this.studyRoomsService.deleteRoom(roomId);
},
5 * 60 * 1000,
);
}
```
- 공부방 인원에 대한 체크. (별도의 users 변수 vs DB에서 조회)
- 기존에 handleDisconnect에서 어차피 공부방 사용자 정보를 조회하기 때문에 이 부분을 사용
=> <BE> 공부방 참여 인원이 없으면 공부방을 삭제한다. 

client/public/images/icons.svg, client/src/components/StudyRoom/ControlBar.tsx, client/src/components/StudyRoom/MediaSelectModal.tsx, client/tailwind.config.js
resolve #110 
1.5
- 카메라⋅마이크 선택 버튼 구현
- 카메라⋅마이크 선택 모달 구현
=> <FE> 카메라⋅마이크 선택 레이아웃 구현

client/src/components/StudyRoom/Chat.tsx, client/src/components/StudyRoom/ControlBar.tsx, client/src/components/StudyRoom/MediaSelectModal.tsx, client/src/components/StudyRoom/StudyRoom.tsx, client/src/hooks/useWebRTC.ts
resolve #191 
1
- 읽지 않은 채팅 수 표시 구현
=> <FE> 읽지 않은 채팅 수 표시 구현

client/src/hooks/useWebRTC.ts
resolve #195 
0.5
- 사용가능한 디바이스가 없어도 방 입장 가능하도록 수정
=> <FE> 디바이스없이 방 입장 시 오류 해결

client/src/hooks/useWebRTC.ts
resolve #198 
0.5
- 사용 가능한 디바이스가 없는 사용자와의 연결이 완전하도록 수정
- 사용 가능한 디바이스가 없는 경우 AudioContext API를 사용하여 무음의 더미 트랙을 만들어서 전송하도록 함
=> <FE> 사용 가능한 디바이스가 없는 사용자와의 연결이 완전하도록 수정

client/src/hooks/useWebRTC.ts
resolve #203 
0.5
- 누락된 코드 추가
```typescript
localStreamRef.current = await navigator.mediaDevices.getUserMedia({
audio: { deviceId: { ideal: 'default' } },
});
```
=> <FE> 카메라가 켜지지 않는 오류 수정

server/src/study-room/study-room.controller.ts
resolve #200
2시간
- coturn 서버 REST API 인증방식용 설정 파일 수정
- nestjs STUN, TURN 서버 인증정보 발급후 응답 API 구현
- TURN 서버의 인증정보를 안전하게 사용하는 방법을 많이 고민했습니다.
- [API 명세서](https://www.notion.so/4a06a020061d4ad4a62ede62960e03bc?v=a07e2ebfa0544e2e9a1c58fd586a3c3e&p=c05df5065da3422585399efed47bcfc9&pm=s)
- [개발일지](https://www.notion.so/4e85c1fdc265402e9526676132b008bc?v=88054bde3de042a9bed8a84700b723d3&p=db2cd1b0ddc24369bf5c8e0953b5abbf&pm=s)
- https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api
=> <BE> STUN, TURN 서버 인증정보 발급 API 구현

client/package.json, client/src/components/Home/Home.tsx, client/src/components/StudyRoom/MediaSelectModal.tsx, client/src/components/StudyRoom/VideoGrid.tsx, client/src/components/StudyRoomList/AddItemModal.tsx, client/src/components/StudyRoomList/ItemCard.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx, client/src/components/StudyRoomList/index.tsx, client/src/hooks/useWebRTC.ts, client/src/socket/signalingClient.ts, package-lock.json
resolve #194 
1
- 비동기 과정에서 로딩 스피너 구현
- coturn 인증 정보 발급 API 연결
- key 값을 넣지 않아 생기는 오류 수정
- 잘못 연결된 주소 : `localhost:5173/study-room/api/study-room/credentials`
- localhost와 api 사이에 `study-room`이 삽입되어있음
- 수정 전
```typescript
const API_BASE_URL = import.meta.env.DEV ? 'api' : import.meta.env.VITE_SIGNALING_SERVER_URL;
```
- 수정 후
```typescript
const API_BASE_URL = import.meta.env.DEV ? '/api' : import.meta.env.VITE_SIGNALING_SERVER_URL;
```
- [react-spinners](https://www.davidhu.io/react-spinners/)
=> <FE> 비동기 과정에서 로딩 스피너 표시

client/src/components/StudyRoom/VideoOverlay.tsx, client/src/components/StudyRoomList/AddItemModal.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx
resolve #209 
0.5
- VideoOverlay 상대방 닉네임에 truncate 적용
- 공부방 생성 모달의 비밀방 체크박스 재정렬
- 비밀방 입장 모달의 비밀번호 입력칸에 autoFocus 적용
=> <FE> truncate 적용 및 체크박스 재정렬

client/src/components/StudyRoomList/ItemCard.tsx
resolve #211 
0.1
- 공개방 입장 시  navigate가 두 번 실행되고 있던 부분을 수정
=> <FE> 공부방에서 뒤로가기를 한 번해도 나갈 수 있도록 수정

README.md
resolve #215 
- readme 업데이트 (prettier 적용을 위해 이슈 생성하여 작업했습니다)
=> <Common> README 업데이트

client/src/socket/signalingClient.ts
resolve #217 
4
- PeerConnection 메모리 누수 문제 해결
- [PeerConnection 메모리 누수 문제](https://www.notion.so/PeerConnection-151fab6ff8a780e98b53d25cc0a51e4b?pvs=4)
=> <FE> PeerConnection 메모리 누수 문제 해결

server/src/app.module.ts, server/src/signaling-server/signaling-server.gateway.ts
resolve #227 
10분
- mesh namespace 설정
- 중복된 sfuServerModule 설정
=> <BE> mesh namespace 설정 및 중복된 sfuServerModule 삭제

client/src/stores/useWebRTCStore.ts
resolve #229 
0
- 공부방 소켓 접속 시 signaling server url 뒤에 /mesh 추가
=> <FE> 소켓 접속 시 signaling server url 뒤에 /mesh 추가

server/src/study-room/study-room.service.ts
resolve #221 
30분
- 주석 수정
- 최대 인원인 방에 접근 시 에러 반환
```json
{
"canAccess": false,
"error": {
"message": "Room is already full",
"error": "Forbidden",
"statusCode": 403
}
}
```
- https://www.notion.so/4a06a020061d4ad4a62ede62960e03bc?v=a07e2ebfa0544e2e9a1c58fd586a3c3e&p=ea1be7921bde4bff8d05b71eda3019a0&pm=s
=> <BE> 최대 인원 초과 방 접근 제한

server/src/sfu-server/sfu-server.service.ts
=> <BE> SFU 방은 방을 나가도 삭제 타이머가 돌지 않도록 수정

server/src/study-room/study-room.service.ts
resolve #236 
10분
- 존재하지 않는 방이면 에러를 반환하도록 수정
=> <BE> 존재하지 않는 study-room 입장 요청 시, 새로운 테스트방이 생성되는 버그 수정

client/package.json, client/src/App.tsx, client/src/components/Permission/index.tsx, client/src/components/StudyRoom/ControlBar.tsx, client/src/components/StudyRoom/MediaSelectModal.tsx, client/src/components/StudyRoom/Video.tsx, client/src/components/StudyRoom/VideoGrid.tsx, client/src/components/StudyRoomList/AddItemModal.tsx, client/src/components/StudyRoomList/ItemCard.tsx, client/src/components/StudyRoomList/JoinRoomModal.tsx, client/src/stores/useWebRTCStore.ts, client/src/types/WebRTC.ts, client/src/utils/media.ts, package-lock.json
resolve #231 
9
- 카메라⋅마이크 접근 권한 관리 페이지 구현
- 새로고침 시 탭 로딩 스피너가 계속 도는 문제 해결
- 새로고침 시 탭 로딩 스피너가 계속 도는데 모든 동작이 문제없이 실행되는 현상..
- `localStream` 초기값을 `new MediaStream()`이 아닌 `null`로 지정해주어 해결
=> <FE> 카메라⋅마이크 접근 권한 관리 페이지 구현
